version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    assignees:
      - "vglen"
    labels:
      - "dependencies"
      - "go"
    rebase-strategy: "auto"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    assignees:
      - "vglen"
    labels:
      - "dependencies"
      - "github-actions"
    rebase-strategy: "auto"
    schedule:
      interval: "daily"
      time: "07:15"
      timezone: "UTC"
    open-pull-requests-limit: 5
    groups:
      gha-dependencies:
        patterns:
          - "*"
